<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <StripSymbols>true</StripSymbols>
        <PublishAot>true</PublishAot>

        <ApplicationIcon>../Icon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../RaylibSharp/RaylibSharp.csproj" />
    </ItemGroup>
</Project>
