namespace Examples;

using System;

using RaylibSharp;

public static class ExamplesList
{
    public static readonly Example[] Examples = new Example[]
    {
        //
        new("./resources/images/core_basic_window.png",              CoreBasicWindow.Example,              Raylib.Purple, 1),
        new("./resources/images/core_basic_screen_manager.png",      CoreBasicScreenManager.Example,       Raylib.Purple, 1),
        new("./resources/images/core_2d_camera.png",                 Core2dCamera.Example,                 Raylib.Purple, 2),
        new("./resources/images/core_2d_camera_mouse_zoom.png",      Core2dCameraMouseZoom.Example,        Raylib.Purple, 2),
        new("./resources/images/core_2d_camera_platformer.png",      Core2dCameraPlatformer.Example,       Raylib.Purple, 3),
        // new("./resources/images/core_2d_camera_split_screen.png",    Core2dSplitScreen.Example,            Raylib.Purple, 4),
        new("./resources/images/core_3d_camera_first_person.png",    Core3dCameraFirstPerson.Example,      Raylib.Purple, 2),
        new("./resources/images/core_3d_camera_free.png",            Core3dCameraFree.Example,             Raylib.Purple, 1),
        new("./resources/images/core_3d_camera_mode.png",            Core3dCameraMode.Example,             Raylib.Purple, 1),
        new("./resources/images/core_3d_camera_split_screen.png",    Core3dSplitScreen.Example,            Raylib.Purple, 3),
        new("./resources/images/core_3d_picking.png",                Core3dPicking.Example,                Raylib.Purple, 2),
        new("./resources/images/core_custom_frame_control.png",      CoreCustomFrameControl.Example,       Raylib.Purple, 4),
        new("./resources/images/core_custom_logging.png",            CoreCustomLogging.Example,            Raylib.Purple, 3),
        new("./resources/images/core_drop_files.png",                CoreDropFiles.Example,                Raylib.Purple, 2),
        new("./resources/images/core_input_gamepad.png",             CoreInputGamepad.Example,             Raylib.Purple, 1),
        // new("./resources/images/core_input_gamepad_info.png",        CoreInputGamepadInfo.Example,         Raylib.Purple, 1),
        new("./resources/images/core_input_gestures.png",            CoreInputGestures.Example,            Raylib.Purple, 2),
        new("./resources/images/core_input_keys.png",                CoreInputKeys.Example,                Raylib.Purple, 1),
        new("./resources/images/core_input_mouse.png",               CoreInputMouse.Example,               Raylib.Purple, 1),
        new("./resources/images/core_input_mouse_wheel.png",         CoreInputMouseWheel.Example,          Raylib.Purple, 1),
        new("./resources/images/core_input_multitouch.png",          CoreInputMultitouch.Example,          Raylib.Purple, 1),
        new("./resources/images/core_loading_thread.png",            CoreLoadingThread.Example,            Raylib.Purple, 3),
        new("./resources/images/core_random_values.png",             CoreRandomValues.Example,             Raylib.Purple, 1),
        new("./resources/images/core_scissor_test.png",              CoreScissorTest.Example,              Raylib.Purple, 1),
        new("./resources/images/core_smooth_pixelperfect.png",       CoreSmoothPixelperfect.Example,       Raylib.Purple, 3),
        new("./resources/images/core_storage_values.png",            CoreStorageValues.Example,            Raylib.Purple, 2),
        new("./resources/images/core_vr_simulator.png",              CoreVrSimulator.Example,              Raylib.Purple, 3),
        new("./resources/images/core_window_flags.png",              CoreWindowFlags.Example,              Raylib.Purple, 3),
        new("./resources/images/core_window_letterbox.png",          CoreWindowLetterbox.Example,          Raylib.Purple, 2),
        new("./resources/images/core_window_should_close.png",       CoreWindowShouldClose.Example,        Raylib.Purple, 1),
        new("./resources/images/core_world_screen.png",              CoreWorldScreen.Example,              Raylib.Purple, 2),
        //
        new("./resources/images/shapes_basic_shapes.png",            ShapesBasicShapes.Example,            Raylib.Purple, 1),
        new("./resources/images/shapes_bouncing_ball.png",           ShapesBouncingBall.Example,           Raylib.Purple, 1),
        new("./resources/images/shapes_colors_palette.png",          ShapesColorsPalette.Example,          Raylib.Purple, 2),
        new("./resources/images/shapes_logo_raylib.png",            ShapesLogoRaylib.Example,             Raylib.Purple, 1),
        new("./resources/images/shapes_logo_raylib_anim.png",        ShapesLogoRaylibAnim.Example,         Raylib.Purple, 2),
        new("./resources/images/shapes_rectangle_scaling.png",       ShapesRectangleScaling.Example,       Raylib.Purple, 2),
        new("./resources/images/shapes_lines_bezier.png",            ShapesLinesBezier.Example,            Raylib.Purple, 1),
        new("./resources/images/shapes_collision_area.png",          ShapesCollisionArea.Example,          Raylib.Purple, 2),
        new("./resources/images/shapes_following_eyes.png",          ShapesFollowingEyes.Example,          Raylib.Purple, 2),
        new("./resources/images/shapes_easings_ball_anim.png",       ShapesEasingsBallAnim.Example,        Raylib.Purple, 2),
        new("./resources/images/shapes_easings_box_anim.png",        ShapesEasingsBoxAnim.Example,         Raylib.Purple, 2),
        new("./resources/images/shapes_easings_rectangle_array.png", ShapesEasingsRectangleArray.Example,  Raylib.Purple, 3),
        new("./resources/images/shapes_draw_ring.png",               ShapesDrawRing.Example,               Raylib.Purple, 3),
        new("./resources/images/shapes_draw_circle_sector.png",      ShapesDrawCircleSector.Example,       Raylib.Purple, 3),
        new("./resources/images/shapes_draw_rectangle_rounded.png",  ShapesDrawRectangleRounded.Example,   Raylib.Purple, 3),
        // new("./resources/images/shapes_splines_drawing.png",         ShapesSplinesDrawing.Example,         Raylib.Purple, 3),
        new("./resources/images/shapes_top_down_lights.png",         ShapesTopDownLights.Example,          Raylib.Purple, 4),
        // Textures
        // new("./resources/images/textures_logo_raylib.png",          TexturesLogoRaylib.Example,           Raylib.Purple, 1),
        // new("./resources/images/textures_srcrec_dstrec.png",         TexturesSrcrecDstrec.Example,         Raylib.Purple, 3),
        // new("./resources/images/textures_image_drawing.png",         TexturesImageDrawing.Example,         Raylib.Purple, 2),
        // new("./resources/images/textures_image_generation.png",      TexturesImageGeneration.Example,      Raylib.Purple, 2),
        // new("./resources/images/textures_image_loading.png",         TexturesImageLoading.Example,         Raylib.Purple, 1),
        // new("./resources/images/textures_image_processing.png",      TexturesImageProcessing.Example,      Raylib.Purple, 3),
        // new("./resources/images/textures_image_text.png",            TexturesImageText.Example,            Raylib.Purple, 2),
        // new("./resources/images/textures_to_image.png",              TexturesToImage.Example,              Raylib.Purple, 1),
        // new("./resources/images/textures_raw_data.png",              TexturesRawData.Example,              Raylib.Purple, 3),
        // new("./resources/images/textures_particles_blending.png",    TexturesParticlesBlending.Example,    Raylib.Purple, 1),
        // new("./resources/images/textures_npatch_drawing.png",        TexturesNpatchDrawing.Example,        Raylib.Purple, 3),
        // new("./resources/images/textures_background_scrolling.png",  TexturesBackgroundScrolling.Example,  Raylib.Purple, 1),
        // new("./resources/images/textures_sprite_anim.png",           TexturesSpriteAnim.Example,           Raylib.Purple, 2),
        // new("./resources/images/textures_sprite_button.png",         TexturesSpriteButton.Example,         Raylib.Purple, 2),
        // new("./resources/images/textures_sprite_explosion.png",      TexturesSpriteExplosion.Example,      Raylib.Purple, 2),
        // new("./resources/images/textures_svg_loading.png",           TexturesSvgLoading.Example,           Raylib.Purple, 2),
        // new("./resources/images/textures_bunnymark.png",             TexturesBunnymark.Example,            Raylib.Purple, 3),
        // new("./resources/images/textures_mouse_painting.png",        TexturesMousePainting.Example,        Raylib.Purple, 3),
        // new("./resources/images/textures_blend_modes.png",           TexturesBlendModes.Example,           Raylib.Purple, 1),
        // new("./resources/images/textures_draw_tiled.png",            TexturesDrawTiled.Example,            Raylib.Purple, 3),
        // new("./resources/images/textures_polygon.png",               TexturesPolygon.Example,              Raylib.Purple, 1),
        // new("./resources/images/textures_fog_of_war.png",            TexturesFogOfWar.Example,             Raylib.Purple, 3),
        // new("./resources/images/textures_gif_player.png",            TexturesGifPlayer.Example,            Raylib.Purple, 3),
        // new("./resources/images/textures_textured_curve.png",        TexturesTexturedCurve.Example,        Raylib.Purple, 3),
        // // Text
        // new("./resources/images/text_raylib_fonts.png",              TextRaylibFonts.Example,              Raylib.Purple, 1),
        // new("./resources/images/text_font_spritefont.png",           TextFontSpritefont.Example,           Raylib.Purple, 1),
        // new("./resources/images/text_font_filters.png",              TextFontFilters.Example,              Raylib.Purple, 2),
        // new("./resources/images/text_font_loading.png",              TextFontLoading.Example,              Raylib.Purple, 1),
        // new("./resources/images/text_font_sdf.png",                  TextFontSdf.Example,                  Raylib.Purple, 3),
        // new("./resources/images/text_format_text.png",               TextFormatText.Example,               Raylib.Purple, 1),
        // new("./resources/images/text_input_box.png",                 TextInputBox.Example,                 Raylib.Purple, 2),
        // new("./resources/images/text_writing_anim.png",              TextWritingAnim.Example,              Raylib.Purple, 2),
        // new("./resources/images/text_rectangle_bounds.png",          TextRectangleBounds.Example,          Raylib.Purple, 4),
        // new("./resources/images/text_unicode.png",                   TextUnicode.Example,                  Raylib.Purple, 4),
        // new("./resources/images/text_draw_3d.png",                   TextDraw3d.Example,                   Raylib.Purple, 4),
        // new("./resources/images/text_codepoints_loading.png",        TextCodepointsLoading.Example,        Raylib.Purple, 3),
        // Models
        new("./resources/images/models_animation.png",               ModelsAnimation.Example,              Raylib.Purple, 2),
        new("./resources/images/models_billboard.png",               ModelsBillboard.Example,              Raylib.Purple, 3),
        new("./resources/images/models_box_collisions.png",          ModelsBoxCollisions.Example,          Raylib.Purple, 1),
        new("./resources/images/models_cubicmap.png",                ModelsCubicmap.Example,               Raylib.Purple, 2),
        new("./resources/images/models_first_person_maze.png",       ModelsFirstPersonMaze.Example,        Raylib.Purple, 2),
        new("./resources/images/models_geometric_shapes.png",        ModelsGeometricShapes.Example,        Raylib.Purple, 1),
        new("./resources/images/models_mesh_generation.png",         ModelsMeshGeneration.Example,         Raylib.Purple, 2),
        new("./resources/images/models_mesh_picking.png",            ModelsMeshPicking.Example,            Raylib.Purple, 3),
        new("./resources/images/models_loading.png",                 ModelsLoading.Example,                Raylib.Purple, 1),
        new("./resources/images/models_loading_gltf.png",            ModelsLoadingGltf.Example,            Raylib.Purple, 1),
        new("./resources/images/models_loading_vox.png",             ModelsLoadingVox.Example,             Raylib.Purple, 1),
        new("./resources/images/models_loading_m3d.png",             ModelsLoadingM3d.Example,             Raylib.Purple, 2),
        new("./resources/images/models_orthographic_projection.png", ModelsOrthographicProjection.Example, Raylib.Purple, 1),
        new("./resources/images/models_rlgl_solar_system.png",       ModelsRlglSolarSystem.Example,        Raylib.Purple, 4),
        new("./resources/images/models_yaw_pitch_roll.png",          ModelsYawPitchRoll.Example,           Raylib.Purple, 2),
        new("./resources/images/models_waving_cubes.png",            ModelsWavingCubes.Example,            Raylib.Purple, 3),
        new("./resources/images/models_heightmap.png",               ModelsHeightmap.Example,              Raylib.Purple, 1),
        new("./resources/images/models_skybox.png",                  ModelsSkybox.Example,                 Raylib.Purple, 2),
        new("./resources/images/models_draw_cube_texture.png",       ModelsDrawCubeTexture.Example,        Raylib.Purple, 2),
        // Shaders
        new("./resources/images/shaders_basic_lighting.png",         ShadersBasicLighting.Example,         Raylib.Purple, 4),
        new("./resources/images/shaders_model_shader.png",           ShadersModelShader.Example,           Raylib.Purple, 2),
        new("./resources/images/shaders_shapes_textures.png",        ShadersShapesTextures.Example,        Raylib.Purple, 2),
        new("./resources/images/shaders_custom_uniform.png",         ShadersCustomUniform.Example,         Raylib.Purple, 2),
        new("./resources/images/shaders_postprocessing.png",         ShadersPostprocessing.Example,        Raylib.Purple, 3),
        new("./resources/images/shaders_palette_switch.png",         ShadersPaletteSwitch.Example,         Raylib.Purple, 3),
        new("./resources/images/shaders_raymarching.png",            ShadersRaymarching.Example,           Raylib.Purple, 4),
        new("./resources/images/shaders_texture_drawing.png",        ShadersTextureDrawing.Example,        Raylib.Purple, 2),
        new("./resources/images/shaders_texture_outline.png",        ShadersTextureOutline.Example,        Raylib.Purple, 3),
        // new("./resources/images/shaders_texture_tiling.png",         ShadersTextureTiling.Example,         Raylib.Purple, 2),
        new("./resources/images/shaders_texture_waves.png",          ShadersTextureWaves.Example,          Raylib.Purple, 2),
        new("./resources/images/shaders_julia_set.png",              ShadersJuliaSet.Example,              Raylib.Purple, 3),
        new("./resources/images/shaders_eratosthenes.png",           ShadersEratosthenes.Example,          Raylib.Purple, 3),
        new("./resources/images/shaders_fog.png",                    ShadersFog.Example,                   Raylib.Purple, 3),
        new("./resources/images/shaders_simple_mask.png",            ShadersSimpleMask.Example,            Raylib.Purple, 2),
        new("./resources/images/shaders_hot_reloading.png",          ShadersHotReloading.Example,          Raylib.Purple, 3),
        new("./resources/images/shaders_lightmap.png",               ShadersLightmap.Example,              Raylib.Purple, 3),
        new("./resources/images/shaders_mesh_instancing.png",        ShadersMeshInstancing.Example,        Raylib.Purple, 4),
        new("./resources/images/shaders_multi_sample2d.png",         ShadersMultiSample2d.Example,         Raylib.Purple, 2),
        new("./resources/images/shaders_spotlight.png",              ShadersSpotlight.Example,             Raylib.Purple, 2),
        new("./resources/images/shaders_write_depth.png",            ShadersWriteDepth.Example,            Raylib.Purple, 2),
        new("./resources/images/shaders_hybrid_render.png",          ShadersHybridRender.Example,          Raylib.Purple, 4),
        // new("./resources/images/shaders_deferred_render.png",        ShadersDeferredRender.Example,        Raylib.Purple, 4),
        // Audio
        new("./resources/images/audio_module_playing.png",           AudioModulePlaying.Example,           Raylib.Purple, 1),
        new("./resources/images/audio_music_stream.png",             AudioMusicStream.Example,             Raylib.Purple, 1),
        new("./resources/images/audio_raw_stream.png",               AudioRawStream.Example,               Raylib.Purple, 3),
        new("./resources/images/audio_sound_loading.png",            AudioSoundLoading.Example,            Raylib.Purple, 1),
        // new("./resources/images/audio_sound_multi.png",              AudioSoundMulti.Example,              Raylib.Purple, 2),
        new("./resources/images/audio_stream_effects.png",           AudioStreamEffects.Example,           Raylib.Purple, 4),
        new("./resources/images/audio_mixed_processor.png",          AudioMixedProcessor.Example,          Raylib.Purple, 4),
    };
}

public record Example(string Path, Func<int> Entry, Color Color, int Stars);
