on: [push, workflow_dispatch]
jobs:
    gh-pages:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  path: repo

            - name: Setup .NET7
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "7.0.100"

            - name: Install wasm-tools
              run: |
                  dotnet workload install wasm-tools

            - name: Checkout raylib
              uses: actions/checkout@v3
              with:
                  ref: 4.2.0
                  repository: raysan5/raylib
                  path: RaylibRepo

            - name: Setup emsdk
              uses: mymindstorm/setup-emsdk@v11
              with:
                  version: 3.1.12
                  actions-cache-folder: "emsdk-cache"

            - name: Build raylib for Web
              run: |
                  cd RaylibRepo
                  emcmake cmake \
                    -B artifacts \
                    -D BUILD_EXAMPLES=Off \
                    -D PLATFORM=Web
                  cmake --build artifacts

            - uses: actions/download-artifact@v3
              with:
                  name: raylib.a
                  path: repo/RaylibRepo/artifacts/raylib/libraylib.a
